#!/bin/sh

### BEGIN INIT INFO
# Provides:          sss
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fast tunnel proxy that helps you bypass firewalls
# Description:       A secure socks5 proxy, designed to protect your Internet traffic.
#                    This package contain local and server part of shadowsocks, a fast,
#                    powerful tunnel proxy to bypass firewalls.
### END INIT INFO

# Author: Shell.Xu <shell909090@gmail.com>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC=shadowsocks             # Introduce a short description here
NAME=sss                     # Introduce the short server's name here
DAEMON=/usr/local/bin/sss    # Introduce the server's location here
DAEMON_ARGS=""               # Arguments to run the daemon with
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
LOGFILE=/var/log/$NAME.log

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

case "$1" in
  start)
        $DAEMON start
        ;;
  stop)
        $DAEMON stop
        ;;
  restart)
        $DAEMON restart
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 3
        ;;
esac
